name: Android CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          build-tools-version: '33.0.2'
          platform-version: '33'
          ndk-version: '25.2.9519653'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}

      - name: Validate Gradle Wrapper
        run: |
          if [ ! -f "gradlew" ]; then
            echo "❌ Error: gradlew file is missing!"
            exit 1
          fi
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew clean
          ./gradlew assembleDebug test --stacktrace --scan
          ./gradlew lintDebug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 5
          if-no-files-found: error

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            app/build/test-results/**/*
            app/build/outputs/lint-results/**/*
